{% set version = "11.0.0" %}

package:
  name: av
  # Set post version to indicate our modifications on conda-forge
  version: {{ version }}.post1

source:
  url: https://pypi.io/packages/source/a/av/av-{{ version }}.tar.gz
  sha256: 48223f000a252070f8e700ff634bb7fb3aa1b7bc7e450373029fbdd6f369ac31
  patches:
    - patches/lgpl_tests.patch
    - patches/1061-AVVideoFrame-from_numpy_buffer.patch
    - patches/version.patch

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    # 2022/02/06: hmaarrfk
    # Tests don't seem to be passing on azure with ppc64le
    - python setup.py test                   # [(build_platform == target_platform) and (not ppc64le)]
  run_exports:
    # PyAV now claims to follow semantic versioning
    - {{ pin_subpackage('av') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - pkg-config  # [not win]
  host:
    - python
    - pip
    - cython
    - numpy
    - ffmpeg  {{ ffmpeg }}=lgpl*
    - pillow
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pillow

test:
  commands:
    # But they won't be available if the user chooses the lgpl version
    - python -c "import av; assert 'libx264' not in av.codecs_available"
    - python -c "import av; assert 'libx265' not in av.codecs_available"
    # openh264 should always be available from conda-forge
    - python -c "import av; assert 'libopenh264' in av.codecs_available"
  imports:
    - av
    - av.audio
    - av.audio.fifo

about:
  home: https://github.com/PyAV-Org/PyAV/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic bindings for FFmpeg.

  description: |
    PyAV is a Pythonic binding for FFmpeg or Libav. We aim to provide all of
    the power and control of the underlying library, but manage the gritty
    details as much as possible.
  doc_url: https://pyav.org/docs/develop/
  dev_url: https://github.com/PyAV-Org/PyAV/

extra:
  recipe-maintainers:
    - danielballan
    - mikeboers
    - sdvillal
    - h-vetinari
    - hmaarrfk
